### ISSUE TITLE
Base URL and protocol appears to be missing when calling httpClient->request from getSpeciesName

### ISSUE THREAD

**Issue by therobyouknow** [jbroutier/iucn-api-client#1]
Exception thrown:

`"Invalid URL: scheme is missing in "species/Scolopendra%20abnormis". Did you forget to add "http(s)://"?"`

<img width="541" alt="image" src="https://user-images.githubusercontent.com/1080646/204023267-44b2b650-b26f-4667-99b6-10d139513a02.png">

which calls:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/1080646/204023470-59a41d21-37be-4522-b43e-bf5ed7d4b9df.png">

Background:
Using this code in a custom Drupal module in [Scratchpads2 ](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6564#issuecomment-1326412851)project.

Call stack:
```
Symfony\Component\HttpClient\ScopingHttpClient->request (\home\robdaviswork\work\nhm\scratchpads\scratchpads2\sites\scratchpads\sites\all\libraries\vendor\symfony\http-client\ScopingHttpClient.php:72)
IucnApi\Client->getSpeciesByName (\home\robdaviswork\work\nhm\scratchpads\scratchpads2\sites\scratchpads\sites\all\libraries\vendor\jbroutier\iucn-api-client\src\Client.php:300)
iucn_block_view (\home\robdaviswork\work\nhm\scratchpads\scratchpads2\sites\scratchpads\sites\all\modules\custom\scratchpads\scratchpads_species\modules\iucn\iucn.module:68)
module_invoke (\home\robdaviswork\work\nhm\scratchpads\scratchpads2\sites\scratchpads\includes\module.inc:934)
ajaxblocks_ajax_handler (\home\robdaviswork\work\nhm\scratchpads\scratchpads2\sites\scratchpads\sites\all\modules\contrib\ajaxblocks\ajaxblocks.module:269)
menu_execute_active_handler (\home\robdaviswork\work\nhm\scratchpads\scratchpads2\sites\scratchpads\includes\menu.inc:527)
{main} (\home\robdaviswork\work\nhm\scratchpads\scratchpads2\sites\scratchpads\index.php:21)
```

**Comment by therobyouknow** [comment]
Updated the original starting comment in issue.  I had submitted it incompletely.

**Comment by jbroutier** [comment]
Hello,

I did a few tests and I can’t reproduce the bug. Can you tell me what version of PHP your are using and what version of `symfony/http-client` is present in your `composer.lock` file.

Thanks.

**Comment by therobyouknow** [comment]
7.2

https://github.com/NaturalHistoryMuseum/scratchpads2/blob/master/.ddev/config.yaml

composer.lock file

https://github.com/NaturalHistoryMuseum/scratchpads2/blob/master/composer.lock

thanks for looking into it so far.

**Comment by jbroutier** [comment]
You're using an unsupported version of PHP.

You obviously changed some of the code to make it work with PHP 7.2 and bypassed the compatibility check of Composer., or installed the package in an unusual way. Correct me if I'm wrong. But if that's the case I can't help you.

**Comment by therobyouknow** [comment]
**working modified version for php 7.2, so far for getSpeciesByName** 

Thank you for getting back to me.  Very much appreciate your comment and totally agree about unsupported version of php: 7.2 is old.  

But for unfortunately for me I have to work with it for the time being. Our code base and production currently uses this version. At least until we make more concrete our plans to be able to move to the latest, 8.1 or 8.2 etc.

My changes to `Client::getSpeciesByName` are here:
https://github.com/NaturalHistoryMuseum/scratchpads2/blob/rob/6564-use-v3-iucn-redlist-token-and-restructure-api-handling/sites/all/libraries/vendor/jbroutier/iucn-api-client/src/Client.php#L300

From above, I found that the `base_uri` of the API, i.e. `https://apiv3.iucnredlist.org/api/v3/` and the query `?token=tokenapikey` had to be passed to http->request

Without these changes, I'm not sure how I could have got `getSpeciesByName` to work (i.e. run without stopping due to exceptions), as my xdebug previously showed there was no base_uri or query for the token.  

But as you say you could not reproduce my issue, thank you for looking into it. So my guess is that the syntactical changes in a supported version of php compared with 7.2 enabled some normal execution paths in the code that didn't run for me and for these things to be set up. On that basis, with php 7.2 I had to make my own modifications as shown to get the equivalent behaviour.

I'm very grateful so far for your project and to be able to re-use it.

Given that I've solved this original issue, I will close this issue. 

Thank you very much once again.
